spring:
  datasource:
    url: jdbc:h2:mem:gestore-agenti-test;MODE=LEGACY;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: never   # ‚Üê Stop a schema.sql e data.sql

  flyway:
    enabled: true
    clean-disabled: false
    clean-on-validation-error: true
    locations: classpath:db/migration

  test:
    database:
      replace: none
